apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: strapi
  labels:
    app: strapi
spec:
  selector:
    app: strapi
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-traffic
      port: 1337
      targetPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-deployment
  namespace: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  replicas: 1
  template:
    metadata:
      labels:
        app: strapi
    spec:
      hostAliases:
        - ip: "192.168.1.64"
          hostnames:
            - "auth.digitalready.io"
      containers:
        - name: strapi
          image: localhost:32000/strapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          envFrom:
            - configMapRef:
                name: strapi-config-map
            - secretRef:
                name: strapi-secret